// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx30WOjOMZuFOLd_I_e6bGP9zolodxtjE',
    appId: '1:134556174423:android:70df3b5a6ae46340c3bb12',
    messagingSenderId: '134556174423',
    projectId: 'cpsc4150-readright',
    storageBucket: 'cpsc4150-readright.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwkA3_ukT3xwYZM1af8Ne7KPa-POBWhdI',
    appId: '1:134556174423:ios:1a87fdcb33d64775c3bb12',
    messagingSenderId: '134556174423',
    projectId: 'cpsc4150-readright',
    storageBucket: 'cpsc4150-readright.firebasestorage.app',
    iosBundleId: 'com.example.readright',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOfx_Rmxetsavdz-dxwTM59RkMQpKSmQw',
    appId: '1:134556174423:web:91bbe41f50778da6c3bb12',
    messagingSenderId: '134556174423',
    projectId: 'cpsc4150-readright',
    authDomain: 'cpsc4150-readright.firebaseapp.com',
    storageBucket: 'cpsc4150-readright.firebasestorage.app',
  );
}
